"""
    VATUSA API

       # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "vatusa-core-api-client"
VERSION = "1.0.1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "pydantic==1.10.2",
    "requests==2.28.1",
    "aiohttp==3.8.4",
]

setup(
    name=NAME,
    version=VERSION,
    description="VATUSA Core API Client",
    author="Jon",
    author_email="tech@vatusa.net",
    url="",
    keywords=["VATUSA Core API Client"],
    python_requires=">=3.10",
    install_requires=REQUIRES,
    packages=['vatusa_core'],
    include_package_data=True,
    long_description="""\
       # noqa: E501
    """
)
